// AUTH ACTIONS
export const LOGIN_USER = "LOGIN_USER";
export const LOGINGIN_USER = "LOGINGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CLEAR_USER = "CLEAR_USER";
export const LOADING_USER = "LOADING_USER";
export const SET_ERRORS = "SET_ERRORS";

// EMPLOYEE ACTIONS
export const FETCH_ATTENDANCE = "FETCH_ATTENDANCE";
export const CLEAR_DATA = "CLEAR_DATA";

// ADMIN ACTIONS
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_SINGLE_ATTENDANCE = "FETCH_SINGLE_ATTENDANCE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const SEARCH_EMPLOYEE = "SEARCH_EMPLOYEE";
export const ADDED_AS_ADMIN = "ADDED_AS_ADMIN";
export const SET_ADMIN_ERRORS = "SET_ADMIN_ERRORS";
