// AUTH ACTIONS
export const LOGIN_USER = "LOGIN_USER";
export const LOGINGIN_USER = "LOGINGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CLEAR_USER = "CLEAR_USER";
export const LOADING_USER = "LOADING_USER";
export const SET_ERRORS = "SET_ERRORS";

// EMPLOYEE ACTIONS
export const FETCH_ATTENDANCE = "FETCH_ATTENDANCE";
